close all 

figure();
plot(E, LYAPS_m, 'k-',...
     E, LYAPS_w, 'k-.');
hold on
xline(0.000251, 'k');
xline(0.00146, 'k');
yline(0, 'k');
legend('$\Lambda$',... 
       '$\tilde{\Lambda}$',...
       'Fontsize', 20, 'Location', 'southeast', 'Interpreter', 'latex')
xlabel('$\varepsilon$', 'Fontsize', 30, 'Interpreter', 'latex');
ylabel('Lyapunov Exponents', 'Fontsize', 20, 'Interpreter', 'latex');
annotation('textbox',[.17 .1 .5 0], ...
    'String','$\varepsilon_D$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
annotation('textbox',[.40 .1 .5 0], ...
    'String','$\varepsilon_L$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
hold off

figure();
plot(E_bis, Lyap_con_bis,'r-.',...    
     E_bis, Lyap_exp_bis, 'b--',...
     E_bis, Lyap_w_bis,  'k-');
hold on
xline(0.000251, 'k');
xline(0.00146, 'k');
yline(0, 'k');
legend( '$\Lambda_{\mathrm{cont}}$', '$\Lambda_{\mathrm{exp}}$', '$\overline{\Lambda}$',...        
       'Fontsize', 20, 'Location', 'East', 'Interpreter', 'latex');
xlabel('$\varepsilon$', 'Fontsize', 30, 'Interpreter', 'latex');
ylabel('(conditioned) Lyapunov Exponent', 'Fontsize', 20, 'Interpreter', 'latex');
annotation('textbox',[.17 .1 .5 0], ...
    'String','$\varepsilon_D$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
annotation('textbox',[.40 .1 .5 0], ...
    'String','$\varepsilon_L$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
hold off

figure();
plot(E(5:length(E)), Escape_con(5:length(E)), 'r-.', E, Escape_exp, 'b-');
hold on
xline(0.000251, 'k');
xline(0.00146, 'k');
ylabel('Expected escape time, $\tau$',...
       'Fontsize', 20, 'Interpreter', 'latex');
legend('$\tau_{\mathrm{cont}}$',...
       '$\tau_{\mathrm{exp}}$',...
       'Interpreter', 'latex', 'Fontsize', 20);
xlabel('$\varepsilon$', 'Fontsize', 30, 'Interpreter', 'latex');
ylim([0 100]);
annotation('textbox',[.17 .1 .5 0], ...
    'String','$\varepsilon_D$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
annotation('textbox',[.40 .1 .5 0], ...
    'String','$\varepsilon_L$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
hold off

figure();
plot(E, Lambdas_con, 'r-.', E, Lambdas_exp, 'b-');
hold on
xline(0.000251, 'k');
xline(0.00146, 'k');
ylabel('Escape rate, $\lambda$', 'Fontsize', 20, 'Interpreter', 'latex');
legend('$\lambda_{\mathrm{cont}}$',...
       '$\lambda_{\mathrm{exp}}$',...
       'Interpreter', 'latex', 'Fontsize', 20);
xlabel('$\varepsilon$', 'Fontsize', 30, 'Interpreter', 'latex');
annotation('textbox',[.17 .1 .5 0], ...
    'String','$\varepsilon_D$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
annotation('textbox',[.40 .1 .5 0], ...
    'String','$\varepsilon_L$',...
    'EdgeColor','none', 'Fontsize', 18, 'Interpreter', 'latex');
hold off



